// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: federated.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartTrainingEpoch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         int32                  `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	TotalRounds   int32                  `protobuf:"varint,2,opt,name=total_rounds,json=totalRounds,proto3" json:"total_rounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTrainingEpoch) Reset() {
	*x = StartTrainingEpoch{}
	mi := &file_federated_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTrainingEpoch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTrainingEpoch) ProtoMessage() {}

func (x *StartTrainingEpoch) ProtoReflect() protoreflect.Message {
	mi := &file_federated_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTrainingEpoch.ProtoReflect.Descriptor instead.
func (*StartTrainingEpoch) Descriptor() ([]byte, []int) {
	return file_federated_proto_rawDescGZIP(), []int{0}
}

func (x *StartTrainingEpoch) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *StartTrainingEpoch) GetTotalRounds() int32 {
	if x != nil {
		return x.TotalRounds
	}
	return 0
}

type GlobalModelBroadcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GlobalAverage float64                `protobuf:"fixed64,1,opt,name=global_average,json=globalAverage,proto3" json:"global_average,omitempty"`
	Round         int32                  `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalModelBroadcast) Reset() {
	*x = GlobalModelBroadcast{}
	mi := &file_federated_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalModelBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalModelBroadcast) ProtoMessage() {}

func (x *GlobalModelBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_federated_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalModelBroadcast.ProtoReflect.Descriptor instead.
func (*GlobalModelBroadcast) Descriptor() ([]byte, []int) {
	return file_federated_proto_rawDescGZIP(), []int{1}
}

func (x *GlobalModelBroadcast) GetGlobalAverage() float64 {
	if x != nil {
		return x.GlobalAverage
	}
	return 0
}

func (x *GlobalModelBroadcast) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

type CalculateLocalMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Round         int32                  `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	TotalRounds   int32                  `protobuf:"varint,3,opt,name=total_rounds,json=totalRounds,proto3" json:"total_rounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateLocalMetrics) Reset() {
	*x = CalculateLocalMetrics{}
	mi := &file_federated_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateLocalMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateLocalMetrics) ProtoMessage() {}

func (x *CalculateLocalMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_federated_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateLocalMetrics.ProtoReflect.Descriptor instead.
func (*CalculateLocalMetrics) Descriptor() ([]byte, []int) {
	return file_federated_proto_rawDescGZIP(), []int{2}
}

func (x *CalculateLocalMetrics) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *CalculateLocalMetrics) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *CalculateLocalMetrics) GetTotalRounds() int32 {
	if x != nil {
		return x.TotalRounds
	}
	return 0
}

type LocalMetricsUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Average       float64                `protobuf:"fixed64,1,opt,name=average,proto3" json:"average,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Round         int32                  `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalMetricsUpdate) Reset() {
	*x = LocalMetricsUpdate{}
	mi := &file_federated_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalMetricsUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalMetricsUpdate) ProtoMessage() {}

func (x *LocalMetricsUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_federated_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalMetricsUpdate.ProtoReflect.Descriptor instead.
func (*LocalMetricsUpdate) Descriptor() ([]byte, []int) {
	return file_federated_proto_rawDescGZIP(), []int{3}
}

func (x *LocalMetricsUpdate) GetAverage() float64 {
	if x != nil {
		return x.Average
	}
	return 0
}

func (x *LocalMetricsUpdate) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *LocalMetricsUpdate) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

type RegisterTrainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrainerPid    *PID                   `protobuf:"bytes,1,opt,name=trainer_pid,json=trainerPid,proto3" json:"trainer_pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTrainer) Reset() {
	*x = RegisterTrainer{}
	mi := &file_federated_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTrainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTrainer) ProtoMessage() {}

func (x *RegisterTrainer) ProtoReflect() protoreflect.Message {
	mi := &file_federated_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTrainer.ProtoReflect.Descriptor instead.
func (*RegisterTrainer) Descriptor() ([]byte, []int) {
	return file_federated_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterTrainer) GetTrainerPid() *PID {
	if x != nil {
		return x.TrainerPid
	}
	return nil
}

// RegisterAck je odgovor agregatora na RegisterTrainer - potvrđuje da je
// trener zaveden u listu učesnika. Trener ponavlja registraciju dok ne
// dobije ovaj odgovor (vidi FederatedTrainerActor), čime se sistem
// oporavlja i ako agregator u međuvremenu padne i restartuje se.
type RegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_federated_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_federated_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_federated_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type EpochTimeout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         int32                  `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpochTimeout) Reset() {
	*x = EpochTimeout{}
	mi := &file_federated_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpochTimeout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochTimeout) ProtoMessage() {}

func (x *EpochTimeout) ProtoReflect() protoreflect.Message {
	mi := &file_federated_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochTimeout.ProtoReflect.Descriptor instead.
func (*EpochTimeout) Descriptor() ([]byte, []int) {
	return file_federated_proto_rawDescGZIP(), []int{6}
}

func (x *EpochTimeout) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

var File_federated_proto protoreflect.FileDescriptor

const file_federated_proto_rawDesc = "" +
	"\n" +
	"\x0ffederated.proto\x12\x02pb\x1a\tpid.proto\"M\n" +
	"\x12StartTrainingEpoch\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x05R\x05round\x12!\n" +
	"\ftotal_rounds\x18\x02 \x01(\x05R\vtotalRounds\"S\n" +
	"\x14GlobalModelBroadcast\x12%\n" +
	"\x0eglobal_average\x18\x01 \x01(\x01R\rglobalAverage\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x05R\x05round\"m\n" +
	"\x15CalculateLocalMetrics\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x05R\x05round\x12!\n" +
	"\ftotal_rounds\x18\x03 \x01(\x05R\vtotalRounds\"Z\n" +
	"\x12LocalMetricsUpdate\x12\x18\n" +
	"\aaverage\x18\x01 \x01(\x01R\aaverage\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x14\n" +
	"\x05round\x18\x03 \x01(\x05R\x05round\";\n" +
	"\x0fRegisterTrainer\x12(\n" +
	"\vtrainer_pid\x18\x01 \x01(\v2\a.pb.PIDR\n" +
	"trainerPid\")\n" +
	"\vRegisterAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"$\n" +
	"\fEpochTimeout\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x05R\x05roundB\x12Z\x10agent-project/pbb\x06proto3"

var (
	file_federated_proto_rawDescOnce sync.Once
	file_federated_proto_rawDescData []byte
)

func file_federated_proto_rawDescGZIP() []byte {
	file_federated_proto_rawDescOnce.Do(func() {
		file_federated_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_federated_proto_rawDesc), len(file_federated_proto_rawDesc)))
	})
	return file_federated_proto_rawDescData
}

var file_federated_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_federated_proto_goTypes = []any{
	(*StartTrainingEpoch)(nil),    // 0: pb.StartTrainingEpoch
	(*GlobalModelBroadcast)(nil),  // 1: pb.GlobalModelBroadcast
	(*CalculateLocalMetrics)(nil), // 2: pb.CalculateLocalMetrics
	(*LocalMetricsUpdate)(nil),    // 3: pb.LocalMetricsUpdate
	(*RegisterTrainer)(nil),       // 4: pb.RegisterTrainer
	(*RegisterAck)(nil),           // 5: pb.RegisterAck
	(*EpochTimeout)(nil),          // 6: pb.EpochTimeout
	(*PID)(nil),                   // 7: pb.PID
}
var file_federated_proto_depIdxs = []int32{
	7, // 0: pb.RegisterTrainer.trainer_pid:type_name -> pb.PID
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_federated_proto_init() }
func file_federated_proto_init() {
	if File_federated_proto != nil {
		return
	}
	file_pid_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_federated_proto_rawDesc), len(file_federated_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_federated_proto_goTypes,
		DependencyIndexes: file_federated_proto_depIdxs,
		MessageInfos:      file_federated_proto_msgTypes,
	}.Build()
	File_federated_proto = out.File
	file_federated_proto_goTypes = nil
	file_federated_proto_depIdxs = nil
}
