// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pid.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Parent        *PID                   `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PID) Reset() {
	*x = PID{}
	mi := &file_pid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PID) ProtoMessage() {}

func (x *PID) ProtoReflect() protoreflect.Message {
	mi := &file_pid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PID.ProtoReflect.Descriptor instead.
func (*PID) Descriptor() ([]byte, []int) {
	return file_pid_proto_rawDescGZIP(), []int{0}
}

func (x *PID) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PID) GetParent() *PID {
	if x != nil {
		return x.Parent
	}
	return nil
}

var File_pid_proto protoreflect.FileDescriptor

const file_pid_proto_rawDesc = "" +
	"\n" +
	"\tpid.proto\x12\x02pb\"P\n" +
	"\x03PID\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1f\n" +
	"\x06parent\x18\x03 \x01(\v2\a.pb.PIDR\x06parentB\x12Z\x10agent-project/pbb\x06proto3"

var (
	file_pid_proto_rawDescOnce sync.Once
	file_pid_proto_rawDescData []byte
)

func file_pid_proto_rawDescGZIP() []byte {
	file_pid_proto_rawDescOnce.Do(func() {
		file_pid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pid_proto_rawDesc), len(file_pid_proto_rawDesc)))
	})
	return file_pid_proto_rawDescData
}

var file_pid_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pid_proto_goTypes = []any{
	(*PID)(nil), // 0: pb.PID
}
var file_pid_proto_depIdxs = []int32{
	0, // 0: pb.PID.parent:type_name -> pb.PID
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pid_proto_init() }
func file_pid_proto_init() {
	if File_pid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pid_proto_rawDesc), len(file_pid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pid_proto_goTypes,
		DependencyIndexes: file_pid_proto_depIdxs,
		MessageInfos:      file_pid_proto_msgTypes,
	}.Build()
	File_pid_proto = out.File
	file_pid_proto_goTypes = nil
	file_pid_proto_depIdxs = nil
}
