// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: transport.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ActorTransport_Send_FullMethodName = "/pb.ActorTransport/Send"
)

// ActorTransportClient is the client API for ActorTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActorTransportClient interface {
	Send(ctx context.Context, in *Envelope, opts ...grpc.CallOption) (*Ack, error)
}

type actorTransportClient struct {
	cc grpc.ClientConnInterface
}

func NewActorTransportClient(cc grpc.ClientConnInterface) ActorTransportClient {
	return &actorTransportClient{cc}
}

func (c *actorTransportClient) Send(ctx context.Context, in *Envelope, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ActorTransport_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActorTransportServer is the server API for ActorTransport service.
// All implementations must embed UnimplementedActorTransportServer
// for forward compatibility.
type ActorTransportServer interface {
	Send(context.Context, *Envelope) (*Ack, error)
	mustEmbedUnimplementedActorTransportServer()
}

// UnimplementedActorTransportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActorTransportServer struct{}

func (UnimplementedActorTransportServer) Send(context.Context, *Envelope) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedActorTransportServer) mustEmbedUnimplementedActorTransportServer() {}
func (UnimplementedActorTransportServer) testEmbeddedByValue()                        {}

// UnsafeActorTransportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActorTransportServer will
// result in compilation errors.
type UnsafeActorTransportServer interface {
	mustEmbedUnimplementedActorTransportServer()
}

func RegisterActorTransportServer(s grpc.ServiceRegistrar, srv ActorTransportServer) {
	// If the following call panics, it indicates UnimplementedActorTransportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ActorTransport_ServiceDesc, srv)
}

func _ActorTransport_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Envelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActorTransportServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActorTransport_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActorTransportServer).Send(ctx, req.(*Envelope))
	}
	return interceptor(ctx, in, info, handler)
}

// ActorTransport_ServiceDesc is the grpc.ServiceDesc for ActorTransport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActorTransport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ActorTransport",
	HandlerType: (*ActorTransportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _ActorTransport_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transport.proto",
}
